input "type:keyboard" {
    xkb_options caps:ctrl_modifier
}

# Input method daemon (Fcitx5)
exec --no-startup-id fcitx5 -d --replace

# Toggle input method (English / Vietnamese Unikey)
bindsym $mod+c+k exec fcitx5-remote -t
